sudo: false
dist: trusty
language: java

cache:
  directories:
    - $HOME/.gradle

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL

script:
  - java -version
  - ./gradlew build

#after_success:
#  - ./gradlew coveralls